---
- name: Deploy Superset
  hosts: all
  become: yes
  vars:
    superset_version: "2.1.0"
    superset_home: "/opt/superset"
    superset_venv: "/opt/superset/venv"
    superset_config: "/opt/superset/superset_config.py"
    superset_db: "postgresql://superset:superset@localhost:5432/superset"
    superset_admin_username: "admin"
    superset_admin_password: "admin"
    superset_admin_firstname: "Superset"
    superset_admin_lastname: "Admin"
    superset_admin_email: "admin@superset.com"

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-dev
          - python3-pip
          - python3-venv
          - postgresql
          - postgresql-contrib
          - libpq-dev
        state: present
        update_cache: yes

    - name: Create Superset directory
      file:
        path: "{{ superset_home }}"
        state: directory
        mode: '0755'

    - name: Create virtual environment
      command:
        cmd: "python3 -m venv {{ superset_venv }}"
        creates: "{{ superset_venv }}"

    - name: Upgrade pip
      pip:
        name: pip
        state: latest
        virtualenv: "{{ superset_venv }}"

    - name: Install Superset and dependencies
      pip:
        name: 
          - "apache-superset=={{ superset_version }}"
        virtualenv: "{{ superset_venv }}"
        state: present

    - name: Ensure correct Flask and Werkzeug versions
      pip:
        name:
          - "Flask<2.2,>=2.1.3"
          - "Werkzeug<2.2.0"
        virtualenv: "{{ superset_venv }}"
        state: present
        
    - name: Create Superset config file
      copy:
        dest: "{{ superset_config }}"
        content: |
          SQLALCHEMY_DATABASE_URI = '{{ superset_db }}'
          SECRET_KEY = 'Mr2ZDkpacy5WHpcK33tWWY9vA7sT+DUByun8MAo+gMU='
          WEBSERVER_THREADS = 8
          SUPERSET_WEBSERVER_TIMEOUT = 300

    - name: Initialize Superset database
      command:
        cmd: "{{ superset_venv }}/bin/superset db upgrade"
      environment:
        PYTHONPATH: "{{ superset_home }}"
        SUPERSET_CONFIG_PATH: "{{ superset_config }}"
      register: db_init_result
      ignore_errors: yes


    - name: Create Superset admin user
      command:
        cmd: >
          {{ superset_venv }}/bin/superset fab create-admin
          --username {{ superset_admin_username }}
          --password {{ superset_admin_password }}
          --firstname {{ superset_admin_firstname }}
          --lastname {{ superset_admin_lastname }}
          --email {{ superset_admin_email }}
      environment:
        PYTHONPATH: "{{ superset_home }}"
        SUPERSET_CONFIG_PATH: "{{ superset_config }}"

    - name: Initialize Superset
      command:
        cmd: "{{ superset_venv }}/bin/superset init"
      environment:
        PYTHONPATH: "{{ superset_home }}"
        SUPERSET_CONFIG_PATH: "{{ superset_config }}"

    - name: Create Superset service file
      copy:
        dest: /etc/systemd/system/superset.service
        content: |
          [Unit]
          Description=Superset
          After=network.target

          [Service]
          User=root
          Environment=PYTHONPATH={{ superset_home }}
          Environment=SUPERSET_CONFIG_PATH={{ superset_config }}
          ExecStart={{ superset_venv }}/bin/gunicorn --workers 4 --bind 0.0.0.0:8088 "superset.app:create_app()"
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Start Superset service
      systemd:
        name: superset
        state: started
        enabled: yes
        daemon_reload: yes